# Generated by Django 3.2 on 2021-10-01 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['title', 'description']},
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(help_text='Enter a brief description', max_length=1000),
        ),
    ]
