# Generated by Django 3.2 on 2021-10-15 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20211006_0012'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prueba',
        ),
    ]
